Repository Rookies-Fantasy/rookies-fantasy, pull requests merged in 2025-04, with the labels that each got.

#4 Feature/ENG-11: Code quality workflow
  .github/workflows/ci.yml
  .gitignore
  components/EditScreenInfo.tsx
  components/ExternalLink.tsx
  components/__tests__/StyledText-test.js
  package.json
Labels: devops

#6 Feature/ENG-5: Set up linting and formatting
  .prettierrc
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/(tabs)/two.tsx
  app/+html.tsx
  app/+not-found.tsx
  app/_layout.tsx
  app/modal.tsx
  components/StyledText.tsx
  components/Themed.tsx
  components/useClientOnlyValue.web.ts
  components/useColorScheme.ts
  components/useColorScheme.web.ts
  constants/Colors.ts
  eslint.config.js
  package-lock.json
  package.json
Labels: frontend

#2 Feature/ENG 12: Configure react native app with Firebase and EAS
  .github/workflows/ci.yml
  .gitignore
  app.config.ts
  app.json
  eas.json
  package-lock.json
  package.json
Labels: backend, devops

#7 Bugfix/ENG-22: Rollback to Expo 52
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: bug, devops

#5 Feature/ENG-6: App theme
  .npmrc
  app/(tabs)/_layout.tsx
  app/(tabs)/index.tsx
  app/(tabs)/two.tsx
  app/+not-found.tsx
  app/_layout.tsx
  app/modal.tsx
  assets/fonts/ClashDisplay-Bold.ttf
  assets/fonts/Manrope-Regular.otf
  assets/fonts/SpaceMono-Regular.ttf
  babel.config.js
  components/EditScreenInfo.tsx
  components/StyledText.tsx
  components/Themed.tsx
  components/ui/gluestack-ui-provider/config.ts
  components/ui/gluestack-ui-provider/index.tsx
  components/ui/gluestack-ui-provider/index.web.tsx
  components/ui/gluestack-ui-provider/script.ts
  components/ui/gluestack-ui-provider/types.ts
  components/useClientOnlyValue.ts
  components/useClientOnlyValue.web.ts
  components/useColorScheme.ts
  components/useColorScheme.web.ts
  constants/Colors.ts
  global.css
  gluestack-ui.config.json
  metro.config.js
  nativewind-env.d.ts
  package-lock.json
  package.json
  prettier.config.js
  tailwind.config.js
  tsconfig.json
  utils/typography.plugin.ts
Labels: feature, frontend
